name: "Gilberts To-Do List"
slug: "gilberts-todo"
version: "1.0.6"
description: "A modern to-do list app with tags, drag & drop, and offline support."
image: ghcr.io/gilbert-grape/gilberts-to-do-list/{arch}-gilberts-todo
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: "mdi:checkbox-marked-outline"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - type: data
    read_only: false
